/**
 * REGISTRO DE FUENTES
 * Cada cifra de partida del simulador apunta a una entrada de este registro, y la interfaz
 * la muestra con un icono junto al número. Consultadas el 3 de octubre de 2026.
 *
 *   oficial  → organismo público (INE, BOE, ministerios, Banco de España, CGPJ…)
 *   sector   → informe privado de referencia (portales inmobiliarios, etc.)
 *   derivado → no se publica tal cual, pero se calcula con aritmética a partir de cifras publicadas
 *   supuesto → parámetro del modelo sin fuente publicada: es una hipótesis y se dice
 */
export interface Fuente {
  tipo: 'oficial' | 'sector' | 'derivado' | 'supuesto';
  organismo: string;
  /** Título de la publicación o tabla. */
  titulo: string;
  url?: string;
  periodo: string;
  /** La cifra concreta que se toma de ahí. */
  dato: string;
  /** Cómo se transforma para el modelo, o advertencias. */
  nota?: string;
}

export const FUENTES = {
  // ── Hogares y demografía ─────────────────────────────────────────────────
  hogares: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estadística Continua de Población, 2.º trimestre 2026',
    url: 'https://www.ine.es/dyngs/Prensa/ECP2T26.htm',
    periodo: '1 de julio de 2026 (provisional)',
    dato: '19.874.860 hogares en España; tamaño medio 2,49 personas; +238.585 hogares en un año',
  },
  hogaresProvincia: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estadística Continua de Población: hogares por provincia (tabla 60133)',
    url: 'https://www.ine.es/jaxiT3/Tabla.htm?t=60133',
    periodo: '1 de julio de 2026 (provisional)',
    dato: 'Hogares de cada provincia',
  },
  inmigracion: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estadística de Migraciones y Cambios de Residencia 2024',
    url: 'https://ine.es/dyngs/Prensa/EMCR2024.htm',
    periodo: '2018-2024',
    dato: 'Saldo migratorio exterior 2024: +626.268 personas. Acumulado 2018-2024: +3.194.410 personas',
    nota: 'Se convierte a familias dividiendo entre el tamaño medio del hogar (2,49): ≈ 4.840 familias por semana. El contador «desde 2018» suma el acumulado publicado (≈ 1,28 M de familias hasta 2024) y lo prolonga al ritmo de 2024, porque no hay dato de 2025 ni de 2026.',
  },
  inmigracionProvincia: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'EMCR: saldos por provincia, saldo exterior (tabla 69764)',
    url: 'https://www.ine.es/jaxiT3/Tabla.htm?t=69764',
    periodo: '2024',
    dato: 'Reparto del saldo migratorio exterior entre provincias',
  },
  emancipacion: {
    tipo: 'oficial',
    organismo: 'Consejo de la Juventud de España',
    titulo: 'Observatorio de Emancipación 2025',
    url: 'https://www.cje.org/en/observatorio_2025/',
    periodo: '2025',
    dato: 'Tasa de emancipación 16-29 años: 14,5 %, la más baja de la serie. Edad estimada de emancipación: 30,2 años. Alquilar solo cuesta el 98,7 % del salario joven',
  },
  emancipacionDerivada: {
    tipo: 'derivado',
    organismo: 'INE · Banco de España',
    titulo: 'Familias nuevas que quieren casa cada semana',
    url: 'https://www.ine.es/dyngs/Prensa/PROH20262041.htm',
    periodo: '2026',
    dato: '≈ 3.700 familias por semana además de las que llegan del extranjero',
    nota: 'Cuenta: hogares nuevos previstos por el INE (+205.000 al año) + déficit anual de vivienda del Banco de España (150.000) + hogares que desaparecen y hay que reponer (≈ 130.000) − familias inmigrantes (251.000) ≈ 235.000 al año ≈ 4.500 por semana; de ellas unas 800 ya cuentan como expulsadas del alquiler. El resto, ≈ 3.700, son jóvenes y nuevas familias.',
  },
  edadEmancipacion: {
    tipo: 'oficial',
    organismo: 'Eurostat',
    titulo: 'Age of young people leaving the parental home',
    url: 'https://ec.europa.eu/eurostat/web/products-eurostat-news/w/ddn-20260915-1',
    periodo: '2025',
    dato: 'Edad media de emancipación en España: 30,2 años (UE: 26,3)',
  },
  proyeccionHogares: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Proyección de Hogares 2026-2041',
    url: 'https://www.ine.es/dyngs/Prensa/PROH20262041.htm',
    periodo: '2026-2041',
    dato: '+1,04 % de hogares al año entre 2026 y 2031 (+1.024.156 en cinco años)',
  },
  defunciones: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estimación mensual de nacimientos y defunciones 2025',
    url: 'https://www.ine.es/dyngs/Prensa/EDES_EMN2025.htm',
    periodo: '2025 (provisional)',
    dato: '446.982 defunciones',
    nota: 'El modelo supone que el 0,9 % de los hogares propietarios desaparece cada año (≈ 130.000), dejando una vivienda en herencia. La proporción es una hipótesis.',
  },
  deficit: {
    tipo: 'oficial',
    organismo: 'Banco de España',
    titulo: 'Presentación del Informe Anual 2025',
    url: 'https://www.bde.es/f/webbe/SES/Secciones/Publicaciones/PublicacionesAnuales/InformesAnuales/25/Fich/IIPP-2026-06-18-lopez-salido-es-or.pdf',
    periodo: 'acumulado 2021-2025',
    dato: 'Déficit de unas 750.000 viviendas (viviendas terminadas menos hogares creados)',
    nota: 'El modelo parte de más familias en espera que este déficit porque añade los jóvenes que querrían emanciparse y no pueden; esa parte adicional es una hipótesis.',
  },

  // ── Rentas, salarios y precios al consumo ────────────────────────────────
  smi: {
    tipo: 'oficial',
    organismo: 'BOE',
    titulo: 'Real Decreto 126/2026, salario mínimo interprofesional para 2026',
    url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2026-3815',
    periodo: '2026',
    dato: '1.221 €/mes en 14 pagas = 17.094 €/año (1.424,50 €/mes en 12 pagas). +3,1 % sobre 2025',
    nota: 'Para los años siguientes el modelo hace crecer el SMI al mismo ritmo que los salarios (4 %): entre 2018 y 2026 el SMI subió más que ellos, pero el Gobierno se ha comprometido a mantenerlo en el 60 % del salario medio.',
  },
  rentaHogar: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Encuesta de Condiciones de Vida 2025: renta neta media por hogar (tabla 9949)',
    url: 'https://www.ine.es/jaxiT3/Tabla.htm?t=9949',
    periodo: 'ECV 2025 (ingresos de 2024)',
    dato: '38.994 € por hogar y año; +5,4 % sobre el año anterior',
  },
  rentaProvincia: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Atlas de Distribución de Renta de los Hogares (tabla 53689)',
    url: 'https://www.ine.es/jaxiT3/Tabla.htm?t=53689&L=0',
    periodo: '2023 (último publicado)',
    dato: 'Renta neta media por hogar de cada provincia',
    nota: 'Se actualiza a 2026 con el crecimiento de la renta media nacional entre el Atlas 2023 y la ECV 2025.',
  },
  salarios: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Encuesta Trimestral de Coste Laboral, 2.º trimestre 2026',
    url: 'https://www.ine.es/dyngs/Prensa/ETCL2T26.htm',
    periodo: '2T 2026',
    dato: 'Coste salarial por trabajador: +4,0 % anual',
  },
  ipc: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Indicador adelantado del IPC, septiembre 2026',
    url: 'https://www.ine.es/dyngs/Prensa/adIPC0926.htm',
    periodo: 'septiembre 2026 (adelantado)',
    dato: 'IPC: 4,9 % anual (subyacente 3,1 %)',
    nota: 'Como inflación de fondo para los próximos años el modelo usa la subyacente, 3,1 %. El dinero que imprime el jugador se suma a ella.',
  },
  hipotecas: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estadística de Hipotecas, junio 2026',
    url: 'https://www.ine.es/dyngs/Prensa/H0626.htm',
    periodo: 'junio 2026 (provisional)',
    dato: 'Tipo de interés medio de las nuevas hipotecas sobre vivienda: 2,96 %. Plazo medio: 25 años. Dos de cada tres a tipo fijo',
    nota: 'El modelo redondea el tipo al 2,9 % (media de enero a junio de 2026). Con ese tipo, 25 años y una cuota del 35 % de la renta, el banco presta unos 6,2 años de renta neta.',
  },
  compraventas: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Estadística de Transmisiones de Derechos de la Propiedad',
    url: 'https://www.ine.es/dyngs/Prensa/ETDP1225.htm',
    periodo: '2025',
    dato: 'Unas 700.000 compraventas de vivienda al año',
    nota: 'Sirve para costear las rebajas de impuestos a la compra: el simulador solo mueve una parte de esas compras (las de familias que buscan casa), pero la rebaja fiscal la disfrutan todas.',
  },

  // ── Parque de viviendas ──────────────────────────────────────────────────
  parque: {
    tipo: 'oficial',
    organismo: 'Ministerio de Vivienda y Agenda Urbana',
    titulo: 'Estimación del parque de viviendas, tabla 2 (por provincias)',
    url: 'https://apps.fomento.gob.es/BoletinOnline2/sedal/33102000.XLS',
    periodo: '2025 (provisional)',
    dato: '27.099.556 viviendas en España, de ellas 19.571.428 principales',
  },
  censoVacias: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Censo de Población y Viviendas 2021: viviendas vacías (tabla 59531)',
    url: 'https://www.ine.es/jaxi/Tabla.htm?tpx=59531&L=0',
    periodo: '2021',
    dato: '3.828.307 viviendas vacías de 26,6 M',
  },
  turisticas: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo:
      'Medición del número de viviendas turísticas en España y su capacidad (estadística experimental)',
    url: 'https://www.ine.es/experimental/viv_turistica/experimental_viv_turistica.htm',
    periodo: 'mayo 2026',
    dato: '341.001 viviendas de uso turístico, el 1,28 % del parque; −10,7 % en un año',
    nota: 'El INE lo publica por municipio, pero el simulador aplica el 1,28 % nacional a todas las provincias: en la costa y las islas la proporción real es mucho mayor.',
  },
  tenencia: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Censo de Población y Viviendas 2021: régimen de tenencia por provincia (tabla 59523)',
    url: 'https://www.ine.es/jaxi/Tabla.htm?tpx=59523&L=0',
    periodo: '2021',
    dato: '16,1 % de las viviendas principales en alquiler (2.983.619)',
  },
  viviendaPublica: {
    tipo: 'oficial',
    organismo: 'Ministerio de Vivienda y Agenda Urbana',
    titulo: 'Boletín especial Vivienda Social 2024, Observatorio de Vivienda y Suelo',
    url: 'https://www.mivau.gob.es/recursos_mfom/comodin/recursos/observatoriodeviviendaysueloboletnespecialviviendasocial2024_0.pdf',
    periodo: 'encuesta 2023',
    dato: 'Unas 318.000 viviendas públicas en alquiler (196.842 autonómicas y unas 121.000 municipales)',
    nota: 'Por provincia se reparte el parque autonómico según hogares y se suma el municipal de la capital cuando el boletín lo publica.',
  },
  tenedoresBarcelona: {
    tipo: 'oficial',
    organismo: 'Ajuntament de Barcelona · O-HB',
    titulo:
      'Los grandes tenedores son propietarios del 36 % de los pisos de alquiler habitual de la ciudad',
    url: 'https://www.barcelona.cat/habitatge/es/actualitat/noticies/los-grandes-tenedores-son-propietarios-del-36-de-los-pisos-de-alquiler-habitual-de-la-ciudad-1229148',
    periodo: 'datos de 2021',
    dato: '36 % del alquiler habitual de la ciudad de Barcelona en manos de propietarios con más de 10 viviendas',
    nota: 'Es el único dato municipal publicado que se ha localizado y es de la ciudad, no de la provincia.',
  },
  terminadas: {
    tipo: 'oficial',
    organismo: 'Ministerio de Vivienda y Agenda Urbana',
    titulo:
      'Viviendas libres terminadas (tabla 3.2) y calificaciones definitivas de vivienda protegida (tabla 1.6)',
    url: 'https://apps.fomento.gob.es/BoletinOnline2/?nivel=2&orden=32000000',
    periodo: '2025',
    dato: '93.650 viviendas terminadas: 80.792 libres y 12.858 protegidas (≈ 1.550 y ≈ 250 por semana)',
  },
  visados: {
    tipo: 'oficial',
    organismo: 'Ministerio de Transportes · colegios de aparejadores',
    titulo: 'Visados de dirección de obra nueva 2025',
    url: 'https://www.eleconomista.es/vivienda-inmobiliario/noticias/13799738/02/26/los-visados-de-obra-de-vivienda-nueva-rozaron-las-140000-unidades-en-2025-un-88-mas.html',
    periodo: '2025',
    dato: '139.016 viviendas visadas (+8,8 %), unas 2.670 por semana',
    nota: 'Lo visado hoy es lo que se terminará dentro de uno o dos años. El tope de capacidad del sector del simulador (4.200 viviendas por semana) es una hipótesis: en 2006 se visaron más de 800.000 viviendas, pero la Confederación Nacional de la Construcción dice que faltan 700.000 trabajadores.',
  },
  manoObra: {
    tipo: 'sector',
    organismo: 'Confederación Nacional de la Construcción',
    titulo: 'España necesita trabajadores de la construcción: faltan 700.000 albañiles',
    url: 'https://www.elespanol.com/sociedad/20260806/espana-necesita-trabajadores-construccion-faltan-albaniles-pagan-sueldos-euros-ano/1003744344830_0.html',
    periodo: '2026',
    dato: 'Hacen falta unos 700.000 trabajadores para el relevo generacional y la demanda de obra. Los costes de construcción subieron un 5 % en 2025 por la falta de mano de obra',
  },
  licencias: {
    tipo: 'oficial',
    organismo: 'Consejo Superior de los Colegios de Arquitectos (CSCAE)',
    titulo: 'España cuadruplica el plazo legal para conceder licencias de vivienda',
    url: 'https://www.elespanol.com/invertia/observatorios/vivienda/20260918/espana-cuadruplica-plazo-legal-conceder-licencias-vivienda-espera-encarece-casa-euros/1003744387166_0.html',
    periodo: 'septiembre 2026',
    dato: 'Una licencia de obra tarda 12 meses de media (el límite legal son 3). Cada año de espera encarece la vivienda 13.000 €. La obra en sí tarda de 9 a 14 meses',
    nota: 'El simulador suma licencia (12 meses) y obra (≈ 9 meses): unas 90 semanas desde que se decide construir hasta que se entrega. Agilizar licencias puede recortar hasta 9 meses.',
  },

  // ── Precios ──────────────────────────────────────────────────────────────
  precioVenta: {
    tipo: 'sector',
    organismo: 'idealista',
    titulo: 'Informe de precios de vivienda usada en venta, 3.er trimestre 2026',
    url: 'https://www.idealista.com/news/inmobiliario/vivienda/2026/10/02/916873-la-subida-del-precio-de-la-vivienda-usada-en-venta-llega-al-11-8-anual-en-el-tercer',
    periodo: 'septiembre 2026',
    dato: '2.930 €/m² de media en España, +11,8 % anual. Precio y variación de cada provincia',
    nota: 'Son precios de oferta (anuncio), no de escritura. Se multiplican por la superficie media de la vivienda para obtener el precio por vivienda.',
  },
  precioAlquiler: {
    tipo: 'sector',
    organismo: 'idealista',
    titulo: 'Informe de precios de alquiler, septiembre 2026',
    url: 'https://www.idealista.com/news/inmobiliario/vivienda/2026/10/01/916616-el-precio-del-alquiler-sube-un-5-6-anual-en-septiembre-pero-cae-en-el-ultimo',
    periodo: 'septiembre 2026',
    dato: '15,1 €/m² al mes de media en España, +5,6 % anual. Precio y variación de cada provincia',
    nota: 'Son precios de oferta de contratos nuevos: los contratos antiguos pagan menos. Se multiplican por la superficie media de la vivienda.',
  },

  // ── Mercado: propiedad, oferta, desahucios, impuestos ────────────────────
  tenenciaEcv: {
    tipo: 'oficial',
    organismo: 'INE',
    titulo: 'Encuesta de Condiciones de Vida 2025: hogares por régimen de tenencia (tabla 4566)',
    url: 'https://www.ine.es/jaxiT3/Tabla.htm?t=4566',
    periodo: '2025',
    dato: 'Propiedad 73,3 % · alquiler a precio de mercado 16,7 % · alquiler reducido 3,5 % · cesión 6,5 %',
    nota: 'El reparto provincial del Censo 2021 se escala para que el total nacional de alquiler sea el 20,2 % de 2025.',
  },
  propiedadAlquiler: {
    tipo: 'oficial',
    organismo: 'Banco de España',
    titulo: 'Informe Anual 2023, capítulo 4: El mercado de la vivienda en España',
    url: 'https://www.bde.es/f/webbe/SES/Secciones/Publicaciones/PublicacionesAnuales/InformesAnuales/23/Fich/InfAnual_2023_Cap4.pdf',
    periodo: 'datos de 2022-2023',
    dato: 'Del alquiler de mercado, el 92 % es de particulares y el 8 % de personas jurídicas. Los particulares con más de 10 viviendas tienen como máximo el 7 %',
    nota: 'Solo hay dato nacional: se aplica el mismo reparto a todas las provincias. Para la vivienda vacía y en venta no hay estadística de titularidad; se asume el mismo reparto.',
  },
  ofertaVenta: {
    tipo: 'oficial',
    organismo: 'Banco de España',
    titulo: 'Documento Ocasional 2433: El mercado de la vivienda residencial en España',
    url: 'https://www.bde.es/f/webbe/SES/Secciones/Publicaciones/PublicacionesSeriadas/DocumentosOcasionales/24/Fich/do2433.pdf',
    periodo: 'media 2016-2023',
    dato: 'Unas 820.000 viviendas anunciadas en venta en portales',
    nota: 'No se ha encontrado el stock actual; idealista publica que la oferta en venta cayó un 7 % anual en el 2T 2026, así que hoy es probablemente menor.',
  },
  ofertaAlquiler: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Viviendas anunciadas en alquiler y sin inquilino',
    nota: 'No existe una cifra pública del stock vivo de anuncios de alquiler. El modelo parte del 0,8 % de las viviendas alquiladas. Como referencia, el Observatorio del Alquiler cifra en 683.920 las viviendas ofertadas en alquiler a lo largo de 2025.',
  },
  lanzamientos: {
    tipo: 'oficial',
    organismo: 'Consejo General del Poder Judicial',
    titulo: 'Efectos de la crisis económica en los órganos judiciales, año 2025',
    url: 'https://www.poderjudicial.es/cgpj/es/Poder-Judicial/En-Portada/Las-ejecuciones-hipotecarias-y-los-concursos-registrados-en-los-organos-judiciales-crecieron-en-2025-un-30---respecto-al-ano-anterior',
    periodo: '2025',
    dato: '25.540 lanzamientos practicados; 18.317 por impago de alquiler (LAU), 4.346 por ejecución hipotecaria',
    nota: 'El modelo usa los 18.317 de alquiler: unos 352 a la semana. La nota del CGPJ contiene una errata (24.540 en la entradilla).',
  },
  noRenovaciones: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Contratos de alquiler que el propietario no renueva',
    nota: 'No hay estadística de no renovaciones. El modelo las hace crecer cuando el alquiler de mercado sube más que las rentas o cuando al propietario deja de compensarle alquilar.',
  },
  superficieVenta: {
    tipo: 'oficial',
    organismo: 'Colegio de Registradores',
    titulo: 'Estadística Registral Inmobiliaria, 2.º trimestre 2026',
    url: 'https://www.registradores.org/documents/d/guest/eri_2t_2026',
    periodo: '2T 2026',
    dato: 'Superficie media de la vivienda transmitida: 100,7 m². Precio medio registrado: 2.487 €/m²',
  },
  superficieAlquiler: {
    tipo: 'oficial',
    organismo: 'Ministerio de Vivienda y Agenda Urbana',
    titulo: 'Observatorio de Vivienda y Suelo, Boletín Anual 2025 (SERPAVI)',
    url: 'https://publicaciones.transportes.gob.es/downloadcustom/sample/4130',
    periodo: '2024',
    dato: 'Vivienda alquilada media: 75,6 m². Renta media de los contratos vigentes: 596 €/mes (8,2 €/m²)',
    nota: 'Los contratos vigentes pagan mucho menos que los nuevos. El simulador usa el precio de oferta actual porque es el que encuentra quien busca casa hoy.',
  },
  rentabilidad: {
    tipo: 'sector',
    organismo: 'idealista',
    titulo: 'La rentabilidad de la vivienda cae hasta el 6,5 % en el segundo trimestre',
    url: 'https://www.idealista.com/news/inmobiliario/vivienda/2026/07/06/904853-la-rentabilidad-de-la-vivienda-cae-hasta-el-6-5-en-el-segundo-trimestre',
    periodo: '2T 2026',
    dato: 'Rentabilidad bruta del alquiler: 6,5 %',
    nota: 'El modelo la calcula por m² con los precios de oferta de cada provincia (en torno al 6 % al inicio).',
  },
  impuestoCompra: {
    tipo: 'oficial',
    organismo: 'Agencia Tributaria',
    titulo: 'Compro una vivienda, ¿tengo que pagar IVA o ITP?',
    url: 'https://sede.agenciatributaria.gob.es/Sede/iva/iva-operaciones-inmobiliarias/compro-vivienda-tengo-que-pagar-itp.html',
    periodo: 'vigente en 2026',
    dato: 'IVA del 10 % en vivienda nueva. En vivienda usada se paga ITP, que fija cada comunidad (entre el 4 % y el 13 %)',
    nota: 'El modelo aplica un 10 % único a toda compra. El rango del ITP procede de un resumen no oficial.',
  },
  esfuerzoBde: {
    tipo: 'oficial',
    organismo: 'Banco de España',
    titulo: 'Síntesis de indicadores 1.5: mercado inmobiliario',
    url: 'https://www.bde.es/webbe/es/estadisticas/compartido/datos/pdf/si_1_5.pdf',
    periodo: '2T 2026',
    dato: 'Precio de la vivienda: 8,4 años de renta bruta del hogar. Esfuerzo teórico de compra: 38 % de la renta',
    nota: 'La banca suele exigir que la cuota no pase del 30-35 % de los ingresos: el simulador usa el 35 %.',
  },
  esfuerzoAlquiler: {
    tipo: 'sector',
    organismo: 'idealista',
    titulo: 'El esfuerzo para alquilar se eleva al 39 %',
    url: 'https://www.idealista.com/news/inmobiliario/vivienda/2026/08/18/910335-el-esfuerzo-para-alquilar-se-eleva-al-39-superando-en-10-puntos-al-necesario-para',
    periodo: '2T 2026',
    dato: 'Alquilar exige el 39 % de los ingresos del hogar',
    nota: 'Sirve de contraste: el objetivo del juego mide el alquiler frente al salario mínimo, que es más exigente.',
  },

  // ── Dinero público ───────────────────────────────────────────────────────
  pge: {
    tipo: 'oficial',
    organismo: 'Ministerio de Hacienda · PGE 2023',
    titulo: 'Política de gasto 26: Acceso a la vivienda y fomento de la edificación',
    url: 'https://www.idealista.com/news/finanzas/economia/2022/10/06/799505-pge-2023-3-472-millones-para-alquiler-social-emancipacion-de-los-jovenes-y-eficiencia',
    periodo: '2023 (últimos presupuestos aprobados)',
    dato: '3.472 M€ al año: 992 M€ de fondos nacionales y 2.480 M€ de fondos europeos',
    nota: 'La cartera del juego recibe 290 M€ al mes (3.472 ÷ 12). Con eso se paga la vivienda protegida que ya se construye hoy y lo que el jugador decida añadir.',
  },
  eurostatVivienda: {
    tipo: 'oficial',
    organismo: 'Eurostat',
    titulo: 'Gasto público en vivienda (COFOG, desarrollo de vivienda)',
    url: 'https://www.articulo14.es/economia/espana-invierte-35-euros-por-persona-en-vivienda-social-frente-a-los-163-euros-de-la-ue-20241204.html',
    periodo: '2023',
    dato: 'España: 0,1 % del PIB (1.714 M€), 35 € por persona. Media de los grandes países de la UE: 163 € por persona',
  },
  planEstatal: {
    tipo: 'oficial',
    organismo: 'BOE',
    titulo: 'Real Decreto 326/2026, Plan Estatal de Vivienda 2026-2030',
    url: 'https://www.boe.es/diario_boe/txt.php?id=BOE-A-2026-8872',
    periodo: '2026-2030',
    dato: '7.000 M€ en cinco años (4.200 del Estado y 2.800 de las comunidades; 800 M€ en 2026). 40 % a vivienda protegida, 30 % a rehabilitación, 30 % a ayudas',
  },
  casa47: {
    tipo: 'oficial',
    organismo: 'Ministerio de Vivienda y Agenda Urbana',
    titulo:
      'El Gobierno transfiere 260 millones más a CASA 47 para construir 1.629 nuevas viviendas asequibles',
    url: 'https://www.mivau.gob.es/el-ministerio/sala-de-prensa/noticias/mar-02062026-1307',
    periodo: 'junio 2026',
    dato: '260 M€ para 1.629 viviendas: unos 160.000 € por vivienda pública',
    nota: 'Es el coste que usa el simulador por cada vivienda pública que se empieza. Casa 47 prevé 13.000 M€ en diez años.',
  },
  costesVpo: {
    tipo: 'oficial',
    organismo: 'Instituto Valenciano de la Edificación (FIVE)',
    titulo: 'Informe sobre los costes de construcción y la Vivienda de Protección Oficial',
    url: 'https://www.five.es/costes-vpo/',
    periodo: '2024',
    dato: 'Construir cuesta 888 €/m² (1.110 €/m² con la escasez de mano de obra). Una VPO de 70 m² útiles con garaje sale por 197.000-215.000 €',
  },
  imprimir: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Cada 1.000 M€ impresos suben la inflación 0,08 puntos durante dos años',
    nota: 'Financiar gasto creando dinero es inflacionista, pero no hay una cifra publicada para España (el BCE lo prohíbe). La magnitud es una convención del juego. Imprimir también resta confianza a los inversores. La cartera vuelve a su presupuesto cada mes: si acaba en números rojos, la diferencia se imprime sola.',
  },

  // ── Leyes reales en las que se inspiran los decretos ─────────────────────
  rdl26: {
    tipo: 'oficial',
    organismo: 'BOE',
    titulo:
      'Real Decreto-ley 26/2026, de 29 de septiembre, de medidas urgentes para la protección de la función social de la vivienda',
    url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2026-20266',
    periodo: 'en vigor desde el 1 de octubre de 2026',
    dato: 'Subida máxima del alquiler del 2 % hasta 2027 · recargo del IBI del 50 al 150 % a pisos turísticos en zonas tensionadas · gravamen del 25 % a los beneficios no repartidos de las SOCIMI · reducción del IRPF de hasta el 100 % a quien alquila barato · deducción del 10 % al inquilino · desahucios de hogares vulnerables suspendidos hasta 2030 · alquiler de temporada limitado a 12 meses con causa',
  },
  rdl27: {
    tipo: 'oficial',
    organismo: 'Provivienda (análisis del RD-ley 27/2026)',
    titulo: 'Reales Decretos-leyes 26/2026 y 27/2026: qué cambia en el alquiler',
    url: 'https://provivienda.org/observatorio/real-decreto-ley-26-2026-que-cambia-en-el-precio-del-alquiler-y-la-vivienda-asequible/',
    periodo: 'octubre 2026',
    dato: 'Contratos que se renuevan en ciclos de 5 años (7 si el casero es empresa) · si el casero no renueva, indemniza con 12 mensualidades · preaviso de 6 meses',
  },
  ley12: {
    tipo: 'oficial',
    organismo: 'BOE',
    titulo: 'Ley 12/2023, de 24 de mayo, por el derecho a la vivienda',
    url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2023-12203',
    periodo: 'vigente',
    dato: 'Zonas de mercado tensionado: donde el alquiler más suministros supera el 30 % de la renta media o el precio subió 3 puntos más que el IPC en cinco años, la comunidad autónoma puede topar los alquileres',
  },
  catalunaTensionada: {
    tipo: 'oficial',
    organismo: 'Incasòl (Generalitat de Catalunya)',
    titulo: 'El alquiler en Cataluña tras un año como zona tensionada',
    url: 'https://trioteca.com/blog/alquiler-cataluna-ley-vivienda-2025/',
    periodo: 'abril-diciembre 2024',
    dato: 'Alquiler medio −3,7 % en las zonas tensionadas (Barcelona −6,4 %). Contratos registrados −61 % (Barcelona −80 %). Contratos de temporada +45 %',
    nota: 'Es la referencia del simulador para el efecto de los topes al alquiler: bajan el precio pero parte de la oferta huye a otros usos.',
  },
  barcelona30: {
    tipo: 'oficial',
    organismo: 'Ajuntament de Barcelona',
    titulo: 'La reserva del 30 % de vivienda protegida: 34 pisos en ocho años',
    url: 'https://metropoliabierta.elespanol.com/economia/20260817/reserva-asignatura-pendiente-collboni-solo-pisos-protegidos-anos/1003742786902_0.html',
    periodo: '2018-2026',
    dato: 'Se esperaban 2.000 viviendas protegidas; se han construido 34. Las licencias de obra nueva en suelo urbano cayeron a unas 60 viviendas al año',
  },
  avalesIco: {
    tipo: 'oficial',
    organismo: 'ICO',
    titulo: 'Avales ICO para la compra de la primera vivienda',
    url: 'https://www.ico.es/en/avales-ico-para-la-compra-de-mi-primera-vivienda',
    periodo: '2024-2027',
    dato: 'El Estado avala el 20 % del préstamo (25 % si la casa es eficiente). 2.500 M€ de presupuesto; en 2025 se concedieron 10.453 avales y se movilizaron 1.344 M€, lejos de las 50.000 compras previstas',
  },
  bonoJoven: {
    tipo: 'oficial',
    organismo: 'La Moncloa',
    titulo: 'Bono Alquiler Joven: qué es y quién puede solicitar la ayuda',
    url: 'https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/vivienda-agenda-urbana/paginas/2024/251024-bono-alquiler-joven-solicitar-ayuda.aspx',
    periodo: '2022-2025',
    dato: '250 € al mes durante dos años para menores de 35 con ingresos bajos. 800 M€ acumulados desde 2022',
    nota: 'En el simulador el bono lo cobra toda familia que firma un alquiler, durante dos años: por eso cuesta mucho más que el programa real, que llega a pocos.',
  },
  impuestoExtranjeros: {
    tipo: 'oficial',
    organismo: 'Congreso de los Diputados (proposición de ley)',
    titulo:
      'Impuesto complementario del 100 % a la compra de vivienda por no residentes extracomunitarios',
    url: 'https://www.fieldfisher.com/es-es/locations/espana/actualidad/potencial-subida-de-impuestos-a-las-viviendas-extracomunitarios',
    periodo: 'presentada en mayo de 2025, sin tramitar',
    dato: 'Propuesta de gravar con un 100 % del valor la compra por personas y empresas no residentes en la UE. No se ha votado',
  },
  socimi: {
    tipo: 'oficial',
    organismo: 'BOE · RD-ley 26/2026',
    titulo: 'Gravamen especial a las SOCIMI',
    url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2026-20266',
    periodo: 'desde 2026',
    dato: 'Gravamen del 25 % sobre los beneficios no distribuidos del alquiler residencial; se reduce a la mitad si más del 80 % de las viviendas son asequibles y desaparece si el beneficio se reinvierte en alquiler asequible',
  },
  ley24cat: {
    tipo: 'oficial',
    organismo: 'Generalitat de Catalunya',
    titulo:
      'Ley 24/2015 de medidas urgentes para afrontar la emergencia en el ámbito de la vivienda',
    url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2015-9725',
    periodo: 'vigente en Cataluña',
    dato: 'Los grandes tenedores deben ofrecer un alquiler social antes de desahuciar a hogares vulnerables; la Generalitat puede ceder obligatoriamente pisos vacíos de grandes tenedores',
  },
  temporada: {
    tipo: 'oficial',
    organismo: 'BOE · RD-ley 26/2026',
    titulo: 'Alquiler de temporada',
    url: 'https://www.boe.es/buscar/doc.php?id=BOE-A-2026-20266',
    periodo: 'desde octubre de 2026',
    dato: 'Un alquiler de temporada necesita una causa real y comprobable y no puede pasar de 12 meses; si no, se convierte en alquiler de vivienda habitual',
  },

  // ── Convenciones del simulador ───────────────────────────────────────────
  resultado: {
    tipo: 'supuesto',
    organismo: 'Simulador',
    titulo: '',
    periodo: '',
    dato: 'Resultado calculado por el simulador',
    nota: 'No es un dato observado: lo calcula el modelo cada semana a partir de las cifras de partida (que sí tienen fuente) y de las reglas de comportamiento (que son supuestos).',
  },
  supuesto: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Parámetro de comportamiento del simulador',
    nota: 'No existe una estadística publicada para este valor. Es una hipótesis de diseño, calibrada para que la situación de partida reproduzca las subidas de precio observadas. Puedes cambiarla en factores.ts o parametros.ts.',
  },
  supuestoDecretos: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Intensidad de los efectos de cada ley',
    nota: 'Las leyes se inspiran en normas reales (el icono de cada una enlaza al BOE o al estudio). El sentido de sus efectos sigue la evidencia disponible, pero los porcentajes y puntos que mueven son hipótesis del juego, no estimaciones empíricas. Se editan en decretos.ts.',
  },
  indicePresion: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Índice de presión de 0 a 100 (puede pasar de 100)',
    nota: 'Indicador propio de cada ciudad: 40 % el alquiler respecto a los ingresos de quien busca casa (100 = el 60 % de sus ingresos), 30 % los años de renta que cuesta comprar (100 = 12 años) y 30 % las familias sin casa (100 = el 15 % de los hogares). No tiene techo en 100: una situación peor sigue sumando.',
  },
  tensionSocial: {
    tipo: 'supuesto',
    organismo: 'Modelo',
    titulo: '',
    periodo: '',
    dato: 'Tensión social de 0 a 100',
    nota: 'Sigue la presión de las ciudades ponderada por sus hogares, y nunca es menor que la presión media de las seis grandes áreas urbanas (Madrid, Barcelona, Valencia, Alicante, Sevilla y Málaga): una presión de 90 allí equivale a tensión 100 y cae el gobierno aunque el resto del país esté tranquilo. Suma además las familias expulsadas de su alquiler (un punto por cada 100 semanales por encima de las 1.000 actuales), la inflación por encima del 3,1 % (cuatro puntos por cada punto de IPC), los números rojos de la cartera y el enfado o alivio de cada ley. Se mueve despacio: tarda unos seis meses en reflejar un cambio.',
  },
  objetivos: {
    tipo: 'supuesto',
    organismo: 'Reglas del juego',
    titulo: '',
    periodo: '',
    dato: 'Metas de la partida',
    nota: 'Las tres metas (95 % de familias con vivienda, compra en 6 años de renta neta con impuestos, alquiler en el 35 % del salario mínimo) las fija el diseño del juego. Seis años de renta neta equivalen a unos cinco de renta bruta, el nivel de España a finales de los noventa (hoy son 8,4 según el Banco de España). El 30-35 % de esfuerzo es el umbral de sobreesfuerzo habitual en la literatura. Con el crédito actual (35 % de la renta, 25 años, 2,9 %) un banco presta 6,2 años de renta: por eso el precio no baja de ahí mientras haya compradores.',
  },
} as const satisfies Record<string, Fuente>;

export type FuenteId = keyof typeof FUENTES;
